version: '2'
services:
    tftest-app:
        image: tftest
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tftest-postgresql:5432/TFTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tftest-postgresql:
        extends:
            file: postgresql.yml
            service: tftest-postgresql
